#!/bin/bash

# Daily AI & Tech Briefing Generator
# Version: 1.2 (全中文输出 & Bark 推送)
# Authors: MOSS & 飞天

set -e

# Configuration
WORKSPACE="/Users/lijian/clawd"
BRIEFING_DIR="$WORKSPACE/briefings"
LOG_DIR="$WORKSPACE/logs"
DATE=$(date +%Y-%m-%d)
BRIEFING_FILE="$BRIEFING_DIR/$DATE.md"

# Create directories if they don't exist
mkdir -p "$BRIEFING_DIR"
mkdir -p "$LOG_DIR"

echo "🚀 Starting Daily Briefing generation for $DATE..."

# Initialize briefing content
cat > "$BRIEFING_FILE" << EOF
# 每日AI技术动态简报 $DATE

> Generated by MOSS & 飞天
> Time: $(date '+%Y-%m-%d %H:%M:%S')

---

EOF

# Function: Fetch OpenClaw Updates (v1.2 - 全中文摘要)
fetch_openclaw_updates() {
    echo "🔍 Fetching OpenClaw updates..."
    local UTILITY_AGENT_SCRIPT="$WORKSPACE/scripts/utility-agent.sh"

    local openclaw_content=$(curl -s https://openclaw.ai/blog 2>/dev/null | \
        grep -o '<h2[^>]*>.*</h2>' | \
        sed 's/<[^>]*>//g' | \
        head -5 || echo "No updates found")

    if [ "$openclaw_content" == "No updates found" ]; then
        local summary_content="暂无最新动态。"
    else
        echo "   - Outsourcing summary to Utility-Agent..."
        local summary_content=$("$UTILITY_AGENT_SCRIPT" --quiet "请将以下OpenClaw最新动态总结为3个中文要点" "$openclaw_content")
    fi

    cat >> "$BRIEFING_FILE" << EOF
## 🦞 OpenClaw 最新动态

$summary_content

**更多信息**: https://openclaw.ai/blog

---
EOF
}

# Function: Fetch GitHub Trending (v1.2 - 全中文摘要)
fetch_github_trending() {
    echo "🔥 Fetching GitHub trending..."
    local UTILITY_AGENT_SCRIPT="$WORKSPACE/scripts/utility-agent.sh"

    local trending_raw=$(curl -s https://github.com/trending 2>/dev/null | \
        grep -o 'href="/[^/]* /[^"]*"' | \
        sed 's/href="//;s/"//g;s/ \/ / - /' | \
        head -10 || echo "")

    # 检查是否成功抓取到内容
    if [ -z "$trending_raw" ]; then
        local summary_content="暂时无法获取 GitHub 热门项目数据（可能需要 JavaScript 渲染）。请访问 [GitHub Trending](https://github.com/trending) 查看最新热门项目。"
    else
        echo "   - Outsourcing summary to Utility-Agent..."
        local summary_content=$("$UTILITY_AGENT_SCRIPT" --quiet "请将以下GitHub热门项目总结为3个中文亮点" "$trending_raw")
    fi

    cat >> "$BRIEFING_FILE" << EOF
## 🔥 GitHub 今日热门

$summary_content

**完整榜单**: https://github.com/trending

---
EOF
}

# Function: Fetch AI News (v1.1 - using Tavily search and Utility-Agent for summary)
fetch_ai_news() {
    echo "🤖 Fetching and summarizing AI news..."

    # 定义我们的搜索工具和效用Agent脚本的路径
    local TAVILY_CLI="npx -y @tavily/cli"
    local UTILITY_AGENT_SCRIPT="$WORKSPACE/scripts/utility-agent.sh"

    # 检查我们的核心工具是否都可用
    if ! command -v npx &> /dev/null || [ ! -f "$UTILITY_AGENT_SCRIPT" ]; then
        echo "⚠️  Tavily CLI or Utility-Agent not found. Skipping AI news section." >> "$BRIEFING_FILE"
        return
    fi
    
    # 1. 使用Tavily搜索最新的AI新闻，获取URL列表
    echo "   - Step 1: Searching for latest AI news..."
    local SEARCH_RESULTS=$($TAVILY_CLI search "latest major AI technology news" --search_depth "advanced" --max_results 3)

    if [ -z "$SEARCH_RESULTS" ]; then
        echo "   - No search results from Tavily. Skipping." >> "$BRIEFING_FILE"
        return
    fi

    # 提取URL
    local URLS=$(echo "$SEARCH_RESULTS" | grep -o 'https://[^ ]*')
    
    # 准备写入简报的最终内容
    local FINAL_AI_NEWS_CONTENT=""

    # 2. 循环处理每一个URL
    for url in $URLS; do
        echo "   - Step 2: Processing article: $url"
        
        # 2a. 使用 curl 获取网页的纯文本内容
        # 我们使用-L来跟随重定向，-s来静默模式
        local ARTICLE_CONTENT=$(curl -sL "$url" | sed -n 's/<[^>]*>//g;/./p' | head -c 20000)

        if [ -z "$ARTICLE_CONTENT" ]; then
            echo "      - Failed to fetch content for $url"
            continue
        fi

        # 2b. 调用我们的"智能钥匙" utility-agent，将摘要任务"外包"出去！
        echo "      - Step 3: Outsourcing summarization to Utility-Agent (Gemini-Flash)..."
        local SUMMARY=$("$UTILITY_AGENT_SCRIPT" --quiet "Please summarize the following news article into one concise paragraph, in Chinese." "$ARTICLE_CONTENT")

        # 将格式化的摘要添加到我们的最终内容中
        FINAL_AI_NEWS_CONTENT+=$(echo -e "### $(echo "$SEARCH_RESULTS" | grep "$url" | sed 's/.*"title": "//;s/".*//')\n\n${SUMMARY}\n\n[阅读原文](${url})\n\n")
    done

    # 3. 将所有处理完的新闻，一次性写入简报文件
    cat >> "$BRIEFING_FILE" << EOF
## 🤖 AI 技术动态 (由 Utility-Agent 强力驱动)

$FINAL_AI_NEWS_CONTENT

---
EOF
}

# Execute all fetch functions
fetch_openclaw_updates
fetch_github_trending
fetch_ai_news

# Add footer
cat >> "$BRIEFING_FILE" << EOF

---

📊 **简报统计**
- 生成时间: $(date '+%Y-%m-%d %H:%M:%S')
- 数据来源: OpenClaw, GitHub, Tavily
- 版本: v1.2 (全中文输出 & Bark 推送)

💡 **反馈与建议**
如需定制简报内容或调整推送时间，请联系 MOSS。
EOF

echo "✅ Briefing generated successfully: $BRIEFING_FILE"

# Output preview
echo ""
echo "📋 Briefing Preview:"
echo "==================="
head -20 "$BRIEFING_FILE"
echo "..."
echo "(Full briefing saved to: $BRIEFING_FILE)"

# Push notification via Bark (v1.1)
BARK_SERVER_URL="http://8.163.19.50:8080"
BARK_DEVICE_KEY="DvyYqQWeMn5nLKu498F2ZV"

# 提取简报的首行作为标题
BRIEFING_TITLE=$(head -n 1 "$BRIEFING_FILE" | sed 's/# //')

# 发送推送
echo "🔔 Sending Bark notification..."

# 使用 Python 来正确处理 JSON 转义（跨平台兼容）
python3 -c "
import json
import sys

with open('$BRIEFING_FILE', 'r') as f:
    content = f.read()

data = {
    'title': '$BRIEFING_TITLE',
    'body': content,
    'group': '每日简报',
    'copy': content,
    'level': 'active',
    'sound': 'bell'
}

print(json.dumps(data, ensure_ascii=False))
" | curl -X POST "$BARK_SERVER_URL/$BARK_DEVICE_KEY" \
  -H "Content-Type: application/json" \
  -d @- > /dev/null 2>&1

echo "✅ Bark notification sent."

# Log completion
echo "$(date '+%Y-%m-%d %H:%M:%S') - Daily briefing generated: $BRIEFING_FILE" >> "$LOG_DIR/daily-briefing.log"

exit 0
